STRINGS = {
    "TR": {
        "title": "Genesys Cloud Raporlama Aracı",
        "sidebar_title": "Menü",
        "menu_reports": "Raporlar",
        "menu_dashboard": "Dashboard (Canlı)",
        "menu_users": "Kullanıcı Yönetimi",
        "select_type": "Tür Seçin",
        "type_user": "Agent Bazlı",
        "type_queue": "Kuyruk Bazlı",
        "report_agent": "Agent Raporu",
        "report_queue": "Kuyruk Raporu",
        "report_detailed": "Detaylı Rapor",
        "select_agents": "Agent Seçin",
        "select_queues": "Kuyruk Seçin",
        "select_date": "Tarih Seçin",
        "fetch_report": "Raporu Getir",
        "fetching_data": "Veriler çekiliyor, lütfen bekleyiniz...",
        "no_data": "Seçilen kriterlere uygun veri bulunamadı.",
        "download_excel": "Excel Olarak İndir",
        "error_missing_creds": "Lütfen Client ID ve Secret giriniz.",
        "welcome": "Hoşgeldiniz! Lütfen sol menüden giriş yapınız.",
        "remember_me": "Beni Hatırla",
        "nOffered": "Gelen Çağrı (nOffered)",
        "nAnswered": "Cevaplanan (nAnswered)",
        "nAbandon": "Kaçan Çağrı (nAbandon)",
        "nTransferred": "Transfer Sayısı (nTransferred)",
        "oServiceLevel": "Servis Seviyesi (oServiceLevel)",
        "tAnswered": "Cevaplanma Süresi (tAnswered)",
        "tAbandon": "Kaçan Çağrı Süresi (tAbandon)",
        "tTalk": "Konuşma Süresi (tTalk)",
        "tAcw": "Çağrı Sonrası İşlem (tAcw)",
        "tHandle": "Toplam İşlem Süresi (tHandle)",
        "tHeld": "Bekletme Süresi (tHeld)",
        "tWait": "Bekleme Süresi (tWait)",
        "tAcd": "ACD / Kuyruk Süresi (tAcd)",
        "tAlert": "Çalma / Uyarı Süresi (tAlert)",
        "col_agent": "Agent Adı",
        "col_username": "Kullanıcı Adı",
        "col_workgroup": "Workgroup Adı",
        "col_avg_handle": "Ort. İşlem Süresi (AvgHandle)",
        "col_login": "İlk Giriş (Login)",
        "col_logout": "Son Çıkış (Logout)",
        "col_staffed_time": "Toplam Staff Süresi",
        "nOutbound": "Dış Arama Adedi (nOutbound)",
        "tOutbound": "Dış Arama Süresi (tOutbound)",
        "nNotResponding": "Cevapsız/Reddedilen (nNotResponding)",
        "nConsult": "Danışma Araması (nConsult)",
        "nConsultConnected": "Bağlanan Danışma (nConsultConnected)",
        "nConsultAnswered": "Cevaplanan Danışma (nConsultAnswered)",
        "nConsultTransferred": "Danışma Transferi (nConsultTransferred)",
        "nBlindTransferred": "+Yönlenen (nBlindTransferred)",
        "nConnected": "Bağlanan Çağrı (nConnected)",
        "nOverSla": "SLA Aşan Çağrı (nOverSla)",
        "nError": "Hatalı Çağrı (nError)",
        "nWrapup": "Sonuç Kodu Adedi (nWrapup)",
        "nAlert": "Çalma Adedi (nAlert)",
        "nHandled": "Agent Kapatma (nHandled)",
        "tTalkComplete": "Tamamlanan Konuşma (tTalkComplete)",
        "tHeldComplete": "Tamamlanan Bekletme (tHeldComplete)",
        "tFlowOut": "Flow Çıkış Süresi (tFlowOut)",
        "tVoicemail": "Sesli Mesaj Süresi (tVoicemail)",
        "tOrganizationResponse": "Org. Cevap Süresi (tOrganizationResponse)",
        "tAcdWait": "ACD Bekleme Süresi (tAcdWait)",
        "tContacting": "Arama/Bağlanma Süresi (tContacting)",
        "tMeal": "Yemek Süresi (tMeal)",
        "tMeeting": "Toplantı Süresi (tMeeting)",
        "tAvailable": "Hazır Süresi (tAvailable)",
        "tBusy": "Meşgul Süresi (tBusy)",
        "tAway": "Uzakta Süresi (tAway)",
        "tTraining": "Eğitim Süresi (tTraining)",
        "tOnQueue": "Havuz Süresi (tOnQueue)",
        "start_time": "Başlangıç Saati",
        "end_time": "Bitiş Saati",
        "granularity": "Periyot (Kırılım)",
        "per_day": "Günlük",
        "per_hour": "Saatlik",
        "per_30min": "30 Dakikalık",
        "live_stat": "Canlı Durum",
        "total": "Toplam",
        "waiting": "Bekleyen",
        "interacting": "Görüşmede",
        "service_level": "Servis Seviyesi",
        "auto_refresh": "Otomatik Yenile (10 sn)",
        "agent_status": "Agent Durumu",
        "total_agents": "Toplam Agent",
        "available_agents": "Müsait Agent",
        "login_agents": "Login Agent",
        "idle_agents": "Boşta Agent",
        "agent": "On Queue",
        "on_queue_agents": "Kuyrukta (On Queue)",
        "available": "Uygun (Available)",
        "busy": "Meşgul (Busy)",
        "away": "Uzakta/Mola (Away)",
        "offline": "Çevrimdışı (Offline)",
        "on_queue": "Kuyrukta (On Queue)",
        "not_responding": "Cevapsız (Not Responding)",
        "general_status": "Genel Durum (Toplam)",
        "avg_service_level": "Ort. Servis Seviyesi",
        "add_group": "➕ Yeni Grup Ekle",
        "delete_group": "🗑️ Grubu Sil",
        "edit_group": "✏️ Düzenle",
        "group_name": "Grup Adı",
        "select_queues": "Kuyruk Seçin",
        "card_size": "Boyut",
        "small": "Küçük",
        "medium": "Orta",
        "large": "Büyük",
        "save": "Kaydet",
        "cancel": "İptal",
        "metrics_to_show": "Metrikler",
        "no_queue_selected": "Kuyruk seçilmedi",
        "mode_live": "Canlı",
        "mode_yesterday": "Dün",
        "mode_date": "Tarih",
        "daily_stat": "Günlük İstatistikler",
        "no_live_data": "Canlı veri bulunmuyor",
        "offered": "Gelen",
        "answered": "Cevaplanan",
        "abandoned": "Kaçan",
        "answer_rate": "Cevap Oranı",
        "fill_gaps": "Boşlukları Doldur",
        "metrics_label": "Metrikler",
        "col_interval": "Aralık",
        "size_small": "Küçük",
        "size_medium": "Orta",
        "size_large": "Büyük",
        "report_type": "Rapor Türü",
        "detailed_report": "Detaylı Rapor",
        "select_workgroups": "Kuyrukları Seçin",
        "select_queues_for_group": "Grup için Kuyrukları Seçin",
        "group_title_placeholder": "Grup Başlığı Giriniz",
        "save_view": "Görünümü Kaydet",
        "delete_view": "Görünümü Sil",
        "select_view": "Kayıtlı Görünüm Seçin",
        "export_config": "Yapılandırmayı Dışa Aktar",
        "import_config": "Yapılandırmayı İçe Aktar",
        "preset_name": "Görünüm Adı",
        "view_saved": "Görünüm başarıyla kaydedildi.",
        "view_deleted": "Görünüm silindi.",
        "config_imported": "Yapılandırma başarıyla yüklendi. Sayfayı yenileyin.",
        "config_import_error": "Yapılandırma yüklenirken hata oluştu.",
        "no_view_selected": "Görünüm seçilmedi",
        "col_direction": "Yön (In/Out)",
        "col_ani": "Arayan (ANI)",
        "col_dnis": "Aranan (DNIS)",
        "col_wrapup": "Sonuç Kodu",
        "col_media": "Medya Türü",
        "col_duration": "Süre",
        "col_disconnect": "Kapanış Nedeni",
        "col_alert": "Çalma Süresi",
        "col_hold_count": "Bekletme Sayısı",
        "col_connection": "Cevap Durumu",
        "col_username": "Kullanıcı Adı",
        "interaction_search": "Etkileşim Arama (Detay)",
        "chat_detail": "Chat Detay Raporu (Attributes)",
        "missed_interactions": "Kaçan Çağrılar Raporu (Voice & Chat)",
        "media_type": "Medya Tipi",
        "general": "Genel Rapor",
        "general_settings": "Genel Ayarlar",
        "detailed": "Detaylı Rapor (Eski)",
        "agent_report": "Agent Raporu (Özet)",
        "queue_report": "Kuyruk Raporu (Özet)",
        "admin_panel": "Admin Paneli",
        "api_usage": "API Kullanımı",
        "error_logs": "Hata Kayıtları",
        "total_api_calls": "Toplam API Çağrısı",
        "total_errors": "Toplam Hata",
        "uptime": "Uygulama Çalışma Süresi",
        "endpoint_usage": "Endpoint Bazlı Kullanım",
        "hourly_traffic": "Son 24 Saatlik API Trafiği",
        "system_errors": "Sistem Hata Kayıtları (Son 100)",
        "api_settings": "API Ayarları",
        "genesys_api_creds": "Genesys API Bilgileri",
        "login_genesys": "Giriş (Genesys)",
        "logout_genesys": "Oturumu Kapat (Genesys)",
        "org_code": "Organizasyon Kodu",
        "utc_offset": "UTC Zaman Farkı (Saat)",
        "username": "Kullanıcı Adı",
        "password": "Şifre",
        "remember_me": "Beni Hatırla",
        "login": "Giriş Yap",
        "login_title": "Uygulama Girişi",
        "select_columns": "Sütunları Seçin",
        "fetch_missed_report": "Kaçan Çağrıları Getir",
        "fetch_interactions": "Etkileşimleri Getir",
        "fetch_chat_data": "Chat Verilerini Getir",
        "chat_detail_info": "Bu rapor, webchat, whatsapp, message gibi yazılı etkileşimlerin detaylarını ve 'Participant Data' verilerini içerir.",
        "missed_interactions_info": "Bu rapor, seçilen tarih aralığındaki CEVAPLANMAYAN (Kaçan) sesli ve yazılı etkileşimleri listeler.",
        "interaction_search_info": "Bu rapor, seçilen tarih aralığındaki çağrı, chat ve diğer etkileşimleri listeler.",
        "media_type_help": "Boş bırakılırsa tüm medya tipleri dahil edilir.",
        "fetching_details_info": "Detay veriler {} kayıt için çekiliyor... (Bu işlem biraz sürebilir)",
        "advanced_filters": "Rapor Ayarları & Filtreler",
        "add_new_user": "Yeni Kullanıcı Ekle",
        "generate_password_btn": "Şifre Oluştur",
        "password_help": "Otomatik şifre oluşturmak için yukarıdaki butonu kullanın",
        "role": "Rol",
        "allowed_metrics": "İzinli Metrikler (Boş bırakılırsa hepsi seçilir)",
        "add": "Ekle",
        "save": "Kaydet",
        "export_config": "Yapılandırmayı Dışa Aktar",
        "import_config": "Yapılandırmayı İçe Aktar",
        "layout": "Yerleşim",
        "mode": "Mod",
        "mode_live": "Canlı",
        "mode_yesterday": "Dün",
        "mode_date": "Tarih Seç",
        "auto_refresh": "Oto Güncelleme",
        "agent_panel": "Agent Paneli",
        "call_panel": "Görüşme Paneli",
        "call_panel_refresh": "Hemen Yenile",
        "call_panel_live_only": "Görüşme paneli sadece CANLI modda görünür.",
        "call_panel_need_live": "Bekleyen çağrıları listelemek için canlı kuyruk verisi gerekir.",
        "call_panel_notif_connecting": "Notifications bağlantısı kuruluyor...",
        "call_panel_topic_limit": "Kuyruk sayısı çok yüksek. Bildirimler sadece seçilen gruptaki kuyruklara bağlandı.",
        "agent_panel_notif_connecting": "Agent paneli için bildirimler bağlanıyor...",
        "agent_panel_topic_limit": "Agent sayısı çok yüksek. Bildirimler sınırlı kullanıcıyla başlatıldı.",
        "no_waiting_calls": "Bekleyen çağrı yok.",
        "add_group": "Grup Ekle",
        "settings": "Ayarlar",
        "logout_app": "Çıkış Yap",
        "saved_views": "Kayıtlı Raporlar",
        "preset_name_placeholder": "Yeni Görünüm İsmi",
        "menu_org_settings": "Organizasyon Ayarları",
        "organization": "Organizasyon",
        "org_management": "Organizasyon Yönetimi",
        "org_restricted": "Organizasyon yönetimi sadece varsayılan org adminine açıktır.",
        "org_add": "Organizasyon Ekle",
        "org_delete": "Organizasyon Sil",
        "org_code_label": "Organizasyon Kodu",
        "admin_username": "Admin Kullanıcı Adı",
        "admin_password": "Admin Şifresi",
        "create_org": "Organizasyon Oluştur",
        "delete_org": "Organizasyonu Sil",
        "confirm_delete_org": "Bu işlem org kullanıcılarını ve yerel org dosyalarını siler",
        "no_orgs_found": "Organizasyon bulunamadı.",
        "no_deletable_orgs": "Silinebilecek organizasyon yok.",
        "org_dm_title": "Org DataManager",
        "org_dm_select": "Organizasyon Seç",
        "org_dm_start": "DataManager Başlat",
        "org_dm_stop": "DataManager Durdur",
        "org_dm_running": "Çalışıyor",
        "org_dm_metric_queues": "Metrik Kuyruklar",
        "org_dm_last_update": "Son Güncelleme",
        "org_dm_agent_queues": "Agent Kuyrukları",
        "org_dm_requires_session": "Seçili org için aktif oturum yok.",
        "genesys_not_connected": "Genesys oturumu aktif değil.",
        "dm_disabled_reports": "DataManager durduruldu. Raporlar devre dışı.",
        "refresh_interval": "Canlı Veri Güncelleme Aralığı",
        "seconds_label": "Saniye",
    },
    "EN": {
        "title": "Genesys Cloud Reporting Tool",
        "sidebar_title": "Menu",
        "menu_reports": "Reports",
        "menu_dashboard": "Dashboard (Live)",
        "menu_users": "User Management",
        "select_type": "Select Type",
        "type_user": "Agent Based",
        "type_queue": "Queue Based",
        "select_agents": "Select Agents",
        "select_queues": "Select Queues",
        "select_date": "Select Date",
        "fetch_report": "Fetch Report",
        "fetching_data": "Fetching data, please wait...",
        "no_data": "No data found for the selected criteria.",
        "download_excel": "Download as Excel",
        "error_missing_creds": "Please enter Client ID and Secret.",
        "welcome": "Welcome! Please login from the left menu.",
        "remember_me": "Remember Me",
        "nOffered": "Offered (nOffered)",
        "nAnswered": "Answered (nAnswered)",
        "nAbandon": "Abandoned (nAbandon)",
        "nTransferred": "Transferred (nTransferred)",
        "oServiceLevel": "Service Level (oServiceLevel)",
        "tAnswered": "Answered Time (tAnswered)",
        "tAbandon": "Abandoned Time (tAbandon)",
        "tTalk": "Talk Time (tTalk)",
        "tAcw": "After Call Work (tAcw)",
        "tHandle": "Total Handle Time (tHandle)",
        "tHeld": "Held Time (tHeld)",
        "tWait": "Wait Time (tWait)",
        "tAcd": "ACD Time (tAcd)",
        "tAlert": "Alerting Time (tAlert)",
        "col_agent": "Agent Name",
        "col_username": "Username",
        "col_workgroup": "Workgroup Name",
        "col_avg_handle": "Avg Handle Time (AvgHandle)",
        "col_login": "First Login (Login)",
        "col_logout": "Last Logout (Logout)",
        "col_staffed_time": "Total Staffed Time",
        "nOutbound": "Outbound Calls (nOutbound)",
        "tOutbound": "Outbound Duration (tOutbound)",
        "nNotResponding": "Missing/Not Responding (nNotResponding)",
        "nConsult": "Consult Calls (nConsult)",
        "nConsultConnected": "Consult Connected (nConsultConnected)",
        "nConsultAnswered": "Consult Answered (nConsultAnswered)",
        "nConsultTransferred": "Consult Transferred (nConsultTransferred)",
        "nBlindTransferred": "Blind Transfers (nBlindTransferred)",
        "nConnected": "Connected Calls (nConnected)",
        "nOverSla": "Over SLA Calls (nOverSla)",
        "nError": "Error Calls (nError)",
        "nWrapup": "Wrap-up Count (nWrapup)",
        "nAlert": "Alert Count (nAlert)",
        "nHandled": "Handled Count (nHandled)",
        "tTalkComplete": "Talk Complete (tTalkComplete)",
        "tHeldComplete": "Held Complete (tHeldComplete)",
        "tFlowOut": "Flow Out Time (tFlowOut)",
        "tVoicemail": "Voicemail Time (tVoicemail)",
        "tOrganizationResponse": "Org. Response Time (tOrganizationResponse)",
        "tAcdWait": "ACD Wait Time (tAcdWait)",
        "tContacting": "Contacting Time (tContacting)",
        "tMeal": "Meal Duration (tMeal)",
        "tMeeting": "Meeting Duration (tMeeting)",
        "tAvailable": "Ready Duration (tAvailable)",
        "tBusy": "Busy Duration (tBusy)",
        "tAway": "Away Duration (tAway)",
        "tTraining": "Training Duration (tTraining)",
        "tOnQueue": "On Queue Duration (tOnQueue)",
        "start_time": "Start Time",
        "end_time": "End Time",
        "granularity": "Granularity",
        "per_day": "Daily",
        "per_hour": "Hourly",
        "per_30min": "30 Minutes",
        "live_stat": "Live Status",
        "total": "Total",
        "waiting": "Waiting",
        "interacting": "Interacting",
        "service_level": "Service Level",
        "auto_refresh": "Auto Refresh (10s)",
        "agent_status": "Agent Status",
        "total_agents": "Total Agents",
        "available_agents": "Available Agents",
        "login_agents": "Logged In",
        "idle_agents": "Idle Agents",
        "agent": "On Queue",
        "on_queue_agents": "Agent Total",
        "available": "Available",
        "busy": "Busy",
        "away": "Away",
        "offline": "Offline",
        "on_queue": "On Queue",
        "not_responding": "Not Responding",
        "general_status": "General Status",
        "avg_service_level": "Avg Service Level",
        "add_group": "➕ Add New Group",
        "delete_group": "🗑️ Delete Group",
        "edit_group": "✏️ Edit",
        "group_name": "Group Name",
        "select_queues": "Select Queues",
        "card_size": "Size",
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "save": "Save",
        "cancel": "Cancel",
        "metrics_to_show": "Metrics",
        "no_queue_selected": "No queue selected",
        "mode_live": "Live",
        "mode_yesterday": "Yesterday",
        "mode_date": "Date",
        "daily_stat": "Daily Statistics",
        "no_live_data": "No live data",
        "offered": "Offered",
        "answered": "Answered",
        "abandoned": "Abandoned",
        "answer_rate": "Answer Rate",
        "fill_gaps": "Fill Gaps",
        "metrics_label": "Metrics",
        "col_interval": "Interval",
        "size_small": "Small",
        "size_medium": "Medium",
        "size_large": "Large",
        "report_type": "Report Type",
        "report_agent": "Agent Report",
        "report_queue": "Queue Report",
        "report_detailed": "Detailed Report",
        "detailed_report": "Detailed Report",
        "select_workgroups": "Select Queues",
        "select_queues_for_group": "Select Queues for Group",
        "group_title_placeholder": "Enter Group Title",
        "save_view": "Save View",
        "delete_view": "Delete View",
        "select_view": "Select Saved View",
        "export_config": "Export Configuration",
        "import_config": "Import Configuration",
        "preset_name": "View Name",
        "view_saved": "View saved successfully.",
        "view_deleted": "View deleted.",
        "config_imported": "Configuration imported successfully. Please refresh.",
        "config_import_error": "Error importing configuration.",
        "no_view_selected": "No view selected",
        "col_direction": "Direction",
        "col_ani": "From (ANI)",
        "col_dnis": "To (DNIS)",
        "col_wrapup": "Wrap-up Code",
        "col_media": "Media Type",
        "col_duration": "Duration",
        "col_disconnect": "Disconnect Reason",
        "col_alert": "Alert/Ring Duration",
        "col_hold_count": "Hold Count",
        "col_connection": "Answer Status",
        "col_username": "Username",
        "interaction_search": "Interaction Search (Detail)",
        "chat_detail": "Chat Detail Report (Attributes)",
        "missed_interactions": "Missed Interactions Report (Voice & Chat)",
        "media_type": "Media Type",
        "general": "General Report",
        "general_settings": "General Settings",
        "detailed": "Detailed Report (Legacy)",
        "agent_report": "Agent Report (Summary)",
        "queue_report": "Queue Report (Summary)",
        "admin_panel": "Admin Panel",
        "api_usage": "API Usage",
        "error_logs": "Error Logs",
        "total_api_calls": "Total API Calls",
        "total_errors": "Total Errors",
        "uptime": "App Uptime",
        "endpoint_usage": "Usage by Endpoint",
        "hourly_traffic": "API Traffic (24h)",
        "system_errors": "System Error Logs (Last 100)",
        "api_settings": "API Settings",
        "genesys_api_creds": "Genesys API Credentials",
        "login_genesys": "Login (Genesys)",
        "logout_genesys": "Logout (Genesys)",
        "org_code": "Organization Code",
        "utc_offset": "UTC Offset (Hours)",
        "username": "Username",
        "password": "Password",
        "remember_me": "Remember Me",
        "login": "Login",
        "login_title": "App Login",
        "select_columns": "Select Columns",
        "fetch_missed_report": "Fetch Missed Interactions",
        "fetch_interactions": "Fetch Interactions",
        "fetch_chat_data": "Fetch Chat Data",
        "chat_detail_info": "This report includes details and 'Participant Data' for written interactions like webchat, WhatsApp, and messaging.",
        "missed_interactions_info": "This report lists UNANSWERED (Missed) voice and written interactions for the selected date range.",
        "interaction_search_info": "This report lists calls, chats, and other interactions for the selected date range.",
        "media_type_help": "Leave empty to include all media types.",
        "fetching_details_info": "Fetching detailed attributes for {} records... (This may take a while)",
        "advanced_filters": "Report Settings & Filters",
        "add_new_user": "Add New User",
        "generate_password_btn": "Generate Password",
        "password_help": "Use the button above to generate a secure password",
        "role": "Role",
        "allowed_metrics": "Allowed Metrics (Leave empty for all)",
        "add": "Add",
        "save": "Save",
        "export_config": "Export Configuration",
        "import_config": "Import Configuration",
        "layout": "Layout",
        "mode": "Mode",
        "mode_live": "Live",
        "mode_yesterday": "Yesterday",
        "mode_date": "Date",
        "auto_refresh": "Auto Refresh",
        "agent_panel": "Agent Panel",
        "call_panel": "Call Panel",
        "call_panel_refresh": "Refresh Now",
        "call_panel_live_only": "Call panel is only available in LIVE mode.",
        "call_panel_need_live": "Live queue data is required to list waiting calls.",
        "call_panel_notif_connecting": "Connecting notifications...",
        "call_panel_topic_limit": "Too many queues. Notifications are limited to queues in the selected group.",
        "agent_panel_notif_connecting": "Connecting notifications for the agent panel...",
        "agent_panel_topic_limit": "Too many agents. Notifications started with a limited subset.",
        "no_waiting_calls": "No waiting calls.",
        "add_group": "Add Group",
        "settings": "Settings",
        "logout_app": "Logout App",
        "saved_views": "Saved Views",
        "preset_name_placeholder": "New View Name",
        "menu_org_settings": "Organization Settings",
        "organization": "Organization",
        "org_management": "Organization Management",
        "org_restricted": "Organization management is restricted to the default org admin.",
        "org_add": "Add Organization",
        "org_delete": "Delete Organization",
        "org_code_label": "Organization Code",
        "admin_username": "Admin Username",
        "admin_password": "Admin Password",
        "create_org": "Create Organization",
        "delete_org": "Delete Organization",
        "confirm_delete_org": "This will delete org users and local org files",
        "no_orgs_found": "No organizations found.",
        "no_deletable_orgs": "No deletable organizations.",
        "org_dm_title": "Org DataManager",
        "org_dm_select": "Organization",
        "org_dm_start": "Start DataManager",
        "org_dm_stop": "Stop DataManager",
        "org_dm_running": "Running",
        "org_dm_metric_queues": "Metric Queues",
        "org_dm_last_update": "Last Update",
        "org_dm_agent_queues": "Agent Queues",
        "org_dm_requires_session": "No active session for selected org.",
        "genesys_not_connected": "Genesys session is not active.",
        "dm_disabled_reports": "DataManager is stopped. Reports are disabled.",
        "refresh_interval": "Live Data Refresh Interval",
        "seconds_label": "Seconds",
    }
}

ALL_METRICS = [
    "nOffered", "nAnswered", "nAbandon", "nTransferred", "oServiceLevel",
    "tAnswered", "tAbandon", "tTalk", "tAcw", "tHandle", "tHeld", "tWait", "tAcd", "tAlert",
    "nOutbound", "tOutbound", "nNotResponding", "nConsult", "nConsultTransferred", 
    "nConsultConnected", "nConsultAnswered",
    "nBlindTransferred", "nConnected", "nOverSla", "nError", "nWrapup", "nAlert", "nHandled",
    "tTalkComplete", "tHeldComplete", "tFlowOut", "tVoicemail", "tOrganizationResponse",
    "tAcdWait", "tContacting",
    "tMeal", "tMeeting", "tAvailable", "tBusy", "tAway", "tTraining", "tOnQueue",
    "col_login", "col_logout", "col_staffed_time", "AvgHandle"
]

DEFAULT_METRICS = ["nOffered", "nAnswered", "tAnswered", "tTalk", "tHandle"]

INTERACTION_COLUMNS = [
    "col_direction", "col_ani", "col_dnis", "col_agent", "col_username", "col_workgroup", 
    "col_wrapup", "col_disconnect", "col_media", "col_connection", "col_duration", "col_alert", "col_hold_count",
    "start_time", "end_time"
]

def get_text(lang, key):
    return STRINGS.get(lang, STRINGS["TR"]).get(key, key)
