STRINGS = {
    "TR": {
        "title": "Genesys Cloud Raporlama Aracı",
        "sidebar_title": "Menü",
        "menu_reports": "Raporlar",
        "menu_dashboard": "Dashboard (Canlı)",
        "select_type": "Tür Seçin",
        "type_user": "Agent Bazlı",
        "type_queue": "Kuyruk Bazlı",
        "select_agents": "Agent Seçin",
        "select_queues": "Kuyruk Seçin",
        "select_date": "Tarih Seçin",
        "fetch_report": "Raporu Getir",
        "fetching_data": "Veriler çekiliyor, lütfen bekleyiniz...",
        "no_data": "Seçilen kriterlere uygun veri bulunamadı.",
        "download_excel": "Excel Olarak İndir",
        "error_missing_creds": "Lütfen Client ID ve Secret giriniz.",
        "welcome": "Hoşgeldiniz! Lütfen sol menüden giriş yapınız.",
        "remember_me": "Beni Hatırla",
        "nOffered": "Gelen Çağrı (nOffered)",
        "nAnswered": "Cevaplanan (nAnswered)",
        "nAbandon": "Kaçan Çağrı (nAbandon)",
        "nTransferred": "Transfer Sayısı (nTransferred)",
        "oServiceLevel": "Servis Seviyesi (oServiceLevel)",
        "tAnswered": "Cevaplanma Süresi (tAnswered)",
        "tAbandon": "Kaçan Çağrı Süresi (tAbandon)",
        "tTalk": "Konuşma Süresi (tTalk)",
        "tAcw": "Çağrı Sonrası İşlem (tAcw)",
        "tHandle": "Toplam İşlem Süresi (tHandle)",
        "tHeld": "Bekletme Süresi (tHeld)",
        "tWait": "Bekleme Süresi (tWait)",
        "tAcd": "ACD / Kuyruk Süresi (tAcd)",
        "tAlert": "Çalma / Uyarı Süresi (tAlert)",
        "col_agent": "Agent Adı",
        "col_workgroup": "Workgroup Adı",
        "col_avg_handle": "Ort. İşlem Süresi (AvgHandle)",
        "start_time": "Başlangıç Saati",
        "end_time": "Bitiş Saati",
        "granularity": "Periyot (Kırılım)",
        "per_day": "Günlük",
        "per_hour": "Saatlik",
        "per_30min": "30 Dakikalık",
        "live_stat": "Canlı Durum",
        "total": "Toplam",
        "waiting": "Bekleyen",
        "interacting": "Görüşmede",
        "service_level": "Servis Seviyesi",
        "auto_refresh": "Otomatik Yenile (10 sn)",
        "agent_status": "Agent Durumu",
        "total_agents": "Toplam Agent",
        "available_agents": "Müsait Agent",
        "login_agents": "Login Agent",
        "idle_agents": "Boşta Agent",
        "agent": "On Queue",
        "on_queue_agents": "Agent Total",
        "available": "Uygun (Available)",
        "busy": "Meşgul (Busy)",
        "away": "Uzakta/Mola (Away)",
        "offline": "Çevrimdışı (Offline)",
        "on_queue": "Kuyrukta (On Queue)",
        "not_responding": "Cevapsız (Not Responding)",
        "general_status": "Genel Durum (Toplam)",
        "avg_service_level": "Ort. Servis Seviyesi",
        "add_group": "➕ Yeni Grup Ekle",
        "delete_group": "🗑️ Grubu Sil",
        "edit_group": "✏️ Düzenle",
        "group_name": "Grup Adı",
        "select_queues": "Kuyruk Seçin",
        "card_size": "Boyut",
        "small": "Küçük",
        "medium": "Orta",
        "large": "Büyük",
        "save": "Kaydet",
        "cancel": "İptal",
        "metrics_to_show": "Metrikler",
        "no_queue_selected": "Kuyruk seçilmedi",
        "mode_live": "Canlı",
        "mode_yesterday": "Dün",
        "mode_date": "Tarih",
        "daily_stat": "Günlük İstatistikler",
        "no_live_data": "Canlı veri bulunmuyor",
        "offered": "Gelen",
        "answered": "Cevaplanan",
        "abandoned": "Kaçan",
        "answer_rate": "Cevap Oranı",
        "fill_gaps": "Boşlukları Doldur",
        "metrics_label": "Metrikler",
        "col_interval": "Aralık",
        "size_small": "Küçük",
        "size_medium": "Orta",
        "size_large": "Büyük",
        "report_type": "Rapor Türü",
        "agent_report": "Agent Raporu",
        "workgroup_report": "Kuyruk Raporu",
        "detailed_report": "Detaylı Rapor",
        "select_workgroups": "Kuyrukları Seçin",
        "select_queues_for_group": "Grup için Kuyrukları Seçin",
        "group_title_placeholder": "Grup Başlığı Giriniz",
    },
    "EN": {
        "title": "Genesys Cloud Reporting Tool",
        "sidebar_title": "Menu",
        "menu_reports": "Reports",
        "menu_dashboard": "Dashboard (Live)",
        "select_type": "Select Type",
        "type_user": "Agent Based",
        "type_queue": "Queue Based",
        "select_agents": "Select Agents",
        "select_queues": "Select Queues",
        "select_date": "Select Date",
        "fetch_report": "Fetch Report",
        "fetching_data": "Fetching data, please wait...",
        "no_data": "No data found for the selected criteria.",
        "download_excel": "Download as Excel",
        "error_missing_creds": "Please enter Client ID and Secret.",
        "welcome": "Welcome! Please login from the left menu.",
        "remember_me": "Remember Me",
        "nOffered": "Offered (nOffered)",
        "nAnswered": "Answered (nAnswered)",
        "nAbandon": "Abandoned (nAbandon)",
        "nTransferred": "Transferred (nTransferred)",
        "oServiceLevel": "Service Level (oServiceLevel)",
        "tAnswered": "Answered Time (tAnswered)",
        "tAbandon": "Abandoned Time (tAbandon)",
        "tTalk": "Talk Time (tTalk)",
        "tAcw": "After Call Work (tAcw)",
        "tHandle": "Total Handle Time (tHandle)",
        "tHeld": "Held Time (tHeld)",
        "tWait": "Wait Time (tWait)",
        "tAcd": "ACD Time (tAcd)",
        "tAlert": "Alerting Time (tAlert)",
        "col_agent": "Agent Name",
        "col_workgroup": "Workgroup Name",
        "col_avg_handle": "Avg Handle Time (AvgHandle)",
        "start_time": "Start Time",
        "end_time": "End Time",
        "granularity": "Granularity",
        "per_day": "Daily",
        "per_hour": "Hourly",
        "per_30min": "30 Minutes",
        "live_stat": "Live Status",
        "total": "Total",
        "waiting": "Waiting",
        "interacting": "Interacting",
        "service_level": "Service Level",
        "auto_refresh": "Auto Refresh (10s)",
        "agent_status": "Agent Status",
        "total_agents": "Total Agents",
        "available_agents": "Available Agents",
        "login_agents": "Logged In",
        "idle_agents": "Idle Agents",
        "agent": "On Queue",
        "on_queue_agents": "Agent Total",
        "available": "Available",
        "busy": "Busy",
        "away": "Away",
        "offline": "Offline",
        "on_queue": "On Queue",
        "not_responding": "Not Responding",
        "general_status": "General Status",
        "avg_service_level": "Avg Service Level",
        "add_group": "➕ Add New Group",
        "delete_group": "🗑️ Delete Group",
        "edit_group": "✏️ Edit",
        "group_name": "Group Name",
        "select_queues": "Select Queues",
        "card_size": "Size",
        "small": "Small",
        "medium": "Medium",
        "large": "Large",
        "save": "Save",
        "cancel": "Cancel",
        "metrics_to_show": "Metrics",
        "no_queue_selected": "No queue selected",
        "mode_live": "Live",
        "mode_yesterday": "Yesterday",
        "mode_date": "Date",
        "daily_stat": "Daily Statistics",
        "no_live_data": "No live data",
        "offered": "Offered",
        "answered": "Answered",
        "abandoned": "Abandoned",
        "answer_rate": "Answer Rate",
        "fill_gaps": "Fill Gaps",
        "metrics_label": "Metrics",
        "col_interval": "Interval",
        "size_small": "Small",
        "size_medium": "Medium",
        "size_large": "Large",
        "report_type": "Report Type",
        "agent_report": "Agent Report",
        "workgroup_report": "Queue Report",
        "detailed_report": "Detailed Report",
        "select_workgroups": "Select Queues",
        "select_queues_for_group": "Select Queues for Group",
        "group_title_placeholder": "Enter Group Title",
    }
}

ALL_METRICS = [
    "nOffered", "nAnswered", "nAbandon", "nTransferred", "oServiceLevel",
    "tAnswered", "tAbandon", "tTalk", "tAcw", "tHandle", "tHeld", "tWait", "tAcd", "tAlert"
]

DEFAULT_METRICS = ["nOffered", "nAnswered", "tAnswered", "tTalk", "tHandle"]

def get_text(lang, key):
    return STRINGS.get(lang, STRINGS["TR"]).get(key, key)
